QBShared = QBShared or {}

QBShared.Vehicles = {
	--### GROUND ###--
	-- AUDI
	['rmodrs7'] = {
		['name'] = 'RS7 Sportback',
		['brand'] = 'Audi',
		['model'] = 'rmodrs7',
		['price'] = 50000,
		['category'] = 'Audi',
		['categoryLabel'] = 'Audi',
		['hash'] = `rmodrs7`,
		['shop'] = 'pdm',
	},
	['rs6prior'] = {
		['name'] = 'RS6 Prior',
		['brand'] = 'Audi',
		['model'] = 'rs6prior',
		['price'] = 100000,
		['category'] = 'Audi',
		['categoryLabel'] = 'Audi',
		['hash'] = `rs6prior`,
		['shop'] = 'pdm',
	},
	['a6avant'] = {
		['name'] = 'A6 Avant',
		['brand'] = 'Audi',
		['model'] = 'a6avant',
		['price'] = 100000,
		['category'] = 'Audi',
		['categoryLabel'] = 'Audi',
		['hash'] = `a6avant`,
		['shop'] = 'pdm',
	},

	-- BMW
	['rmodm4gts'] = {
		['name'] = 'M4 GTS',
		['brand'] = 'BMW',
		['model'] = 'rmodm4gts',
		['price'] = 90000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `rmodm4gts`,
		['shop'] = 'pdm',
	},
	['m3e36'] = {
		['name'] = 'M3 E36',
		['brand'] = 'BMW',
		['model'] = 'm3e36',
		['price'] = 83000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `m3e36`,
		['shop'] = 'pdm',
	},
	['rmodBMWi8'] = {
		['name'] = 'I8 Roadster',
		['brand'] = 'BMW',
		['model'] = 'rmodBMWi8',
		['price'] = 50000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `rmodBMWi8`,
		['shop'] = 'pdm',
	},
	['m2f22'] = {
		['name'] = 'M2',
		['brand'] = 'BMW',
		['model'] = 'm2f22',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `m2f22`,
		['shop'] = 'pdm',
	},
	['e92lb'] = {
		['name'] = 'E92 M3',
		['brand'] = 'BMW',
		['model'] = 'e92lb',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `e92lb`,
		['shop'] = 'pdm',
	},
	['BMWM5TOURING'] = {
		['name'] = 'M5 TOURING',
		['brand'] = 'BMW',
		['model'] = 'BMWM5TOURING',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `BMWM5TOURING`,
		['shop'] = 'pdm',
	},
	['22m5'] = {
		['name'] = 'M5 COMPETITION',
		['brand'] = 'BMW',
		['model'] = '22m5',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `22m5`,
		['shop'] = 'pdm',
	},
	['BMWm5e392002wb'] = {
		['name'] = 'E39 M5',
		['brand'] = 'BMW',
		['model'] = 'BMWm5e392002wb',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `BMWm5e392002wb`,
		['shop'] = 'pdm',
	},
	['BMW30jahrem32017wb'] = {
		['name'] = 'F80 M3',
		['brand'] = 'BMW',
		['model'] = 'BMW30jahrem32017wb',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `BMW30jahrem32017wb`,
		['shop'] = 'pdm',
	},
	['m5e60'] = {
		['name'] = 'E60 M5',
		['brand'] = 'BMW',
		['model'] = 'm5e60',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `m5e60`,
		['shop'] = 'pdm',
	},
	['f82'] = {
		['name'] = 'F82 M4',
		['brand'] = 'BMW',
		['model'] = 'f82',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `f82`,
		['shop'] = 'pdm',
	},
	['rmodx6'] = {
		['name'] = 'X6M',
		['brand'] = 'BMW',
		['model'] = 'rmodx6',
		['price'] = 100000,
		['category'] = 'BMW',
		['categoryLabel'] = 'BMW',
		['hash'] = `rmodx6`,
		['shop'] = 'pdm',
	},

	-- BRABUS
	['brabus850'] = {
		['name'] = '850',
		['brand'] = 'BRABUS',
		['model'] = 'brabus850',
		['price'] = 100000,
		['category'] = 'BRABUS',
		['categoryLabel'] = 'BRABUS',
		['hash'] = `brabus850`,
		['shop'] = 'pdm',
	},
	['brabusgt600'] = {
		['name'] = 'GT 600',
		['brand'] = 'BRABUS',
		['model'] = 'brabusgt600',
		['price'] = 80000,
		['category'] = 'BRABUS',
		['categoryLabel'] = 'BRABUS',
		['hash'] = `brabusgt600`,
		['shop'] = 'pdm',
	},
	['w463a1'] = {
		['name'] = 'G Klasse',
		['brand'] = 'BRABUS',
		['model'] = 'w463a1',
		['price'] = 250000,
		['category'] = 'BRABUS',
		['categoryLabel'] = 'BRABUS',
		['hash'] = `w463a1`,
		['shop'] = 'pdm',
	},

	-- Bugatti
    ['neroDRCustoM'] = {
		['name'] = 'Truffade Nero',
		['brand'] = 'Bugatti',
		['model'] = 'neroDRCustoM',
		['price'] = 700000,
		['category'] = 'Bugatti',
		['categoryLabel'] = 'Bugatti',
		['hash'] = `neroDRCustoM`,
		['shop'] = 'pdm',
	},

	-- Chevrolet
	['18camaro'] = {
		['name'] = 'Camaro ZL1',
		['brand'] = 'Chevrolet',
		['model'] = '18camaro',
		['price'] = 100000,
		['category'] = 'Chevrolet',
		['categoryLabel'] = 'Chevrolet',
		['hash'] = `18camaro`,
		['shop'] = 'pdm',
	},
	['impalass'] = {
		['name'] = 'Impala SS 1964',
		['brand'] = 'Chevrolet',
		['model'] = 'impalass',
		['price'] = 100000,
		['category'] = 'Chevrolet',
		['categoryLabel'] = 'Chevrolet',
		['hash'] = `impalass`,
		['shop'] = 'pdm',
	},
	['21camaro'] = {
		['name'] = 'Camaro SS 2021',
		['brand'] = 'Chevrolet',
		['model'] = '21camaro',
		['price'] = 100000,
		['category'] = 'Chevrolet',
		['categoryLabel'] = 'Chevrolet',
		['hash'] = `21camaro`,
		['shop'] = 'pdm',
	},

	-- Dodge
	['redeye'] = {
		['name'] = 'Challenger',
		['brand'] = 'Dodge',
		['model'] = 'redeye',
		['price'] = 115000,
		['category'] = 'Dodge',
		['categoryLabel'] = 'Dodge',
		['hash'] = `redeye`,
		['shop'] = 'pdm',
	},
	['demon'] = {
		['name'] = 'Challenger SRT Demon',
		['brand'] = 'Dodge',
		['model'] = 'demon',
		['price'] = 100000,
		['category'] = 'Dodge',
		['categoryLabel'] = 'Dodge',
		['hash'] = `demon`,
		['shop'] = 'pdm',
	},

	-- Ferrari
	['488misha'] = {
		['name'] = '488 GTB',
		['brand'] = 'Ferrari',
		['model'] = '488misha',
		['price'] = 100000,
		['category'] = 'Ferrari',
		['categoryLabel'] = 'Ferrari',
		['hash'] = `488misha`,
		['shop'] = 'pdm',
	},
	['f10'] = {
		['name'] = 'F10',
		['brand'] = 'Ferrari',
		['model'] = 'f10',
		['price'] = 100000,
		['category'] = 'Ferrari',
		['categoryLabel'] = 'Ferrari',
		['hash'] = `f10`,
		['shop'] = 'pdm',
	},
	['fersf90fh5'] = {
		['name'] = 'SF90 Stradale 2020',
		['brand'] = 'Ferrari',
		['model'] = 'fersf90fh5',
		['price'] = 100000,
		['category'] = 'Ferrari',
		['categoryLabel'] = 'Ferrari',
		['hash'] = `fersf90fh5`,
		['shop'] = 'pdm',
	},

	-- Ford
	['fordt27c'] = {
		['name'] = 'T 1927 C',
		['brand'] = 'Ford',
		['model'] = 'fordt27c',
		['price'] = 100,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `fordt27c`,
		['shop'] = 'pdm',
	},
	['fordt27to'] = {
		['name'] = 'T 1927 TO',
		['brand'] = 'Ford',
		['model'] = 'fordt27to',
		['price'] = 100,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `fordt27to`,
		['shop'] = 'pdm',
	},
	['fordt27t'] = {
		['name'] = 'T 1927 T',
		['brand'] = 'Ford',
		['model'] = 'fordt27t',
		['price'] = 100,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `fordt27t`,
		['shop'] = 'pdm',
	},
	['fordt27r'] = {
		['name'] = 'T 1927 R',
		['brand'] = 'Ford',
		['model'] = 'fordt27r',
		['price'] = 100,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `fordt27r`,
		['shop'] = 'pdm',
	},
	['fordt27p'] = {
		['name'] = 'T 1927 P',
		['brand'] = 'Ford',
		['model'] = 'fordt27p',
		['price'] = 100,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `fordt27p`,
		['shop'] = 'pdm',
	},
	['fordt27ic'] = {
		['name'] = 'T 1927 IC',
		['brand'] = 'Ford',
		['model'] = 'fordt27ic',
		['price'] = 100,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `fordt27ic`,
		['shop'] = 'pdm',
	},
	['fordt27f'] = {
		['name'] = 'T 1927 F',
		['brand'] = 'Ford',
		['model'] = 'fordt27f',
		['price'] = 100,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `fordt27f`,
		['shop'] = 'pdm',
	},
	['domgtcoupe'] = {
		['name'] = 'Mustang RTR',
		['brand'] = 'Ford',
		['model'] = 'domgtcoupe',
		['price'] = 3500,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `domgtcoupe`,
		['shop'] = 'pdm',
	},
	['taco23'] = {
		['name'] = 'Tacoma 2023',
		['brand'] = 'Ford',
		['model'] = 'taco23',
		['price'] = 35000,
		['category'] = 'Ford',
		['categoryLabel'] = 'Ford',
		['hash'] = `taco23`,
		['shop'] = 'pdm',
	},

	-- Fiat
	['multipla'] = {
		['name'] = 'Multipla',
		['brand'] = 'Fiat',
		['model'] = 'multipla',
		['price'] = 97000,
		['category'] = 'Fiat',
		['categoryLabel'] = 'Fiat',
		['hash'] = `multipla`,
		['shop'] = 'pdm',
	},

	-- Hummer
	['tdbhummer'] = {
		['name'] = 'GMC EV',
		['brand'] = 'Hummer',
		['model'] = 'tdbhummer',
		['price'] = 97000,
		['category'] = 'Hummer',
		['categoryLabel'] = 'Hummer',
		['hash'] = `tdbhummer`,
		['shop'] = 'pdm',
	},

	-- Koenigsegg
	['agerarsc'] = {
		['name'] = 'Agera RS Carbon Edition',
		['brand'] = 'Koenigsegg',
		['model'] = 'agerarsc',
		['price'] = 100000,
		['category'] = 'Koenigsegg',
		['categoryLabel'] = 'Koenigsegg',
		['hash'] = `agerarsc`,
		['shop'] = 'pdm',
	},
	['agerars'] = {
		['name'] = 'Agera RS',
		['brand'] = 'Koenigsegg',
		['model'] = 'agerars',
		['price'] = 100000,
		['category'] = 'Koenigsegg',
		['categoryLabel'] = 'Koenigsegg',
		['hash'] = `agerars`,
		['shop'] = 'pdm',
	},
	['jesko'] = {
		['name'] = 'Jesko Absolut',
		['brand'] = 'Koenigsegg',
		['model'] = 'jesko',
		['price'] = 100000,
		['category'] = 'Koenigsegg',
		['categoryLabel'] = 'Koenigsegg',
		['hash'] = `jesko`,
		['shop'] = 'pdm',
	},

	-- Lada
	['lada2107'] = {
		['name'] = 'Riva',
		['brand'] = 'Lada',
		['model'] = 'lada2107',
		['price'] = 9000,
		['category'] = 'Lada',
		['categoryLabel'] = 'Lada',
		['hash'] = `lada2107`,
		['shop'] = 'pdm',
	},

	-- Lamborghini
	['urus2018'] = {
		['name'] = 'Ursus',
		['brand'] = 'Lamborghini',
		['model'] = 'urus2018',
		['price'] = 100000,
		['category'] = 'Lamborghini',
		['categoryLabel'] = 'Lamborghini',
		['hash'] = `urus2018`,
		['shop'] = 'pdm',
	},
	['lb750sv'] = {
		['name'] = 'Aventador',
		['brand'] = 'Lamborghini',
		['model'] = 'lb750sv',
		['price'] = 250000,
		['category'] = 'Lamborghini',
		['categoryLabel'] = 'Lamborghini',
		['hash'] = `lb750sv`,
		['shop'] = 'pdm',
	},
	['Revuelto'] = {
		['name'] = 'Revuelto',
		['brand'] = 'Lamborghini',
		['model'] = 'Revuelto',
		['price'] = 350000,
		['category'] = 'Lamborghini',
		['categoryLabel'] = 'Lamborghini',
		['hash'] = `Revuelto`,
		['shop'] = 'pdm',
	},
	['lwhuracan'] = {
		['name'] = 'Huracan Liberty Walk',
		['brand'] = 'Lamborghini',
		['model'] = 'lwhuracan',
		['price'] = 320000,
		['category'] = 'Lamborghini',
		['categoryLabel'] = 'Lamborghini',
		['hash'] = `lwhuracan`,
		['shop'] = 'pdm',
	},

	-- Lexus
	['lc500'] = {
		['name'] = 'LC500',
		['brand'] = 'Lexus',
		['model'] = 'lc500',
		['price'] = 50000,
		['category'] = 'Lexus',
		['categoryLabel'] = 'Lexus',
		['hash'] = `lc500`,
		['shop'] = 'pdm',
	},
	['lfa10'] = {
		['name'] = 'LFA',
		['brand'] = 'Lexus',
		['model'] = 'lfa10',
		['price'] = 100000,
		['category'] = 'Lexus',
		['categoryLabel'] = 'Lexus',
		['hash'] = `lfa10`,
		['shop'] = 'pdm',
	},
	['RC350'] = {
		['name'] = 'RC350 RB',
		['brand'] = 'Lexus',
		['model'] = 'RC350',
		['price'] = 100000,
		['category'] = 'Lexus',
		['categoryLabel'] = 'Lexus',
		['hash'] = `RC350`,
		['shop'] = 'pdm',
	},
	['is300'] = {
		['name'] = 'IS300',
		['brand'] = 'Lexus',
		['model'] = 'is300',
		['price'] = 100000,
		['category'] = 'Lexus',
		['categoryLabel'] = 'Lexus',
		['hash'] = `is300`,
		['shop'] = 'pdm',
	},

	-- Lucid
	['lucid'] = {
		['name'] = 'Air',
		['brand'] = 'Lucid',
		['model'] = 'lucid',
		['price'] = 1000000,
		['category'] = 'Lucid',
		['categoryLabel'] = 'Lucid',
		['hash'] = `lucid`,
		['shop'] = 'pdm',
	},

	-- Maibatsu
	['sunrise1'] = {
		['name'] = 'Sunrise R',
		['brand'] = 'Maibatsu',
		['model'] = 'sunrise1',
		['price'] = 100000,
		['category'] = 'Maibatsu',
		['categoryLabel'] = 'Maibatsu',
		['hash'] = `sunrise1`,
		['shop'] = 'pdm',
	},
	
	-- Mercedes-Benz
	['gxg63'] = {
		['name'] = 'G63 AMG',
		['brand'] = 'Mercedes-Benz',
		['model'] = 'gxg63',
		['price'] = 100000,
		['category'] = 'Mercedes-Benz',
		['categoryLabel'] = 'Mercedes-Benz',
		['hash'] = `gxg63`,
		['shop'] = 'pdm',
	},
	['rmodgt63'] = {
		['name'] = 'AMG GT63 S COUPE',
		['brand'] = 'Mercedes-Benz',
		['model'] = 'rmodgt63',
		['price'] = 250000,
		['category'] = 'Mercedes-Benz',
		['categoryLabel'] = 'Mercedes-Benz',
		['hash'] = `rmodgt63`,
		['shop'] = 'pdm',
	},
	['amggt63'] = {
		['name'] = 'AMG GT63',
		['brand'] = 'Mercedes-Benz',
		['model'] = 'amggt63',
		['price'] = 100000,
		['category'] = 'Mercedes-Benz',
		['categoryLabel'] = 'Mercedes-Benz',
		['hash'] = `amggt63`,
		['shop'] = 'pdm',
	},
	['rmodamgc63'] = {
		['name'] = 'C63S COUPE WIDEBODY',
		['brand'] = 'Mercedes-Benz',
		['model'] = 'rmodamgc63',
		['price'] = 100000,
		['category'] = 'Mercedes-Benz',
		['categoryLabel'] = 'Mercedes-Benz',
		['hash'] = `rmodamgc63`,
		['shop'] = 'pdm',
	},
	['avtr'] = {
		['name'] = 'vision AVTR',
		['brand'] = 'Mercedes-Benz',
		['model'] = 'avtr',
		['price'] = 100000,
		['category'] = 'Mercedes-Benz',
		['categoryLabel'] = 'Mercedes-Benz',
		['hash'] = `avtr`,
		['shop'] = 'pdm',
	},
	['12cls63'] = {
		['name'] = '2012 CLS63 AMG',
		['brand'] = 'Mercedes-Benz',
		['model'] = '12cls63',
		['price'] = 100000,
		['category'] = 'Mercedes-Benz',
		['categoryLabel'] = 'Mercedes-Benz',
		['hash'] = `12cls63`,
		['shop'] = 'pdm',
	},

	-- Mitsubishi
	['topfoil'] = {
		['name'] = 'Lancer Evolution IX Voltex',
		['brand'] = 'Mitsubishi',
		['model'] = 'topfoil',
		['price'] = 80000,
		['category'] = 'Mitsubishi',
		['categoryLabel'] = 'Mitsubishi',
		['hash'] = `topfoil`,
		['shop'] = 'pdm',
	},

	-- Nissan
	['lwgtr'] = {
		['name'] = 'R35 GTR Liberty Walk',
		['brand'] = 'Nissan',
		['model'] = 'lwgtr',
		['price'] = 180000,
		['category'] = 'Nissan',
		['categoryLabel'] = 'Nissan',
		['hash'] = `lwgtr`,
		['shop'] = 'pdm',
	},
	['skyline'] = {
		['name'] = 'Skyline R34 GTR',
		['brand'] = 'Nissan',
		['model'] = 'skyline',
		['price'] = 140000,
		['category'] = 'Nissan',
		['categoryLabel'] = 'Nissan',
		['hash'] = `skyline`,
		['shop'] = 'pdm',
	},
	['nis15'] = {
		['name'] = 'Silvia S15',
		['brand'] = 'Nissan',
		['model'] = 'nis15',
		['price'] = 100000,
		['category'] = 'Nissan',
		['categoryLabel'] = 'Nissan',
		['hash'] = `nis15`,
		['shop'] = 'pdm',
	},
	['180sx'] = {
		['name'] = '180SX',
		['brand'] = 'Nissan',
		['model'] = '180sx',
		['price'] = 100000,
		['category'] = 'Nissan',
		['categoryLabel'] = 'Nissan',
		['hash'] = `180sx`,
		['shop'] = 'pdm',
	},

	-- Pagani
	['rmodpagani'] = {
		['name'] = 'Huayra Roadster',
		['brand'] = 'Pagani',
		['model'] = 'rmodpagani',
		['price'] = 1500000,
		['category'] = 'Pagani',
		['categoryLabel'] = 'Pagani',
		['hash'] = `rmodpagani`,
		['shop'] = 'pdm',
	},

	-- Tesla
	['jtdcyber'] = {
		['name'] = 'Cybertruck',
		['brand'] = 'Tesla',
		['model'] = 'jtdcyber',
		['price'] = 100000,
		['category'] = 'Tesla',
		['categoryLabel'] = 'Tesla',
		['hash'] = `jtdcyber`,
		['shop'] = 'pdm',
	},
	['tr22'] = {
		['name'] = 'Roadster',
		['brand'] = 'Tesla',
		['model'] = 'tr22',
		['price'] = 100000,
		['category'] = 'Tesla',
		['categoryLabel'] = 'Tesla',
		['hash'] = `tr22`,
		['shop'] = 'pdm',
	},
	['models'] = {
		['name'] = 'Model S',
		['brand'] = 'Tesla',
		['model'] = 'models',
		['price'] = 100000,
		['category'] = 'Tesla',
		['categoryLabel'] = 'Tesla',
		['hash'] = `models`,
		['shop'] = 'pdm',
	},
	['tmodel'] = {
		['name'] = 'Model 3',
		['brand'] = 'Tesla',
		['model'] = 'tmodel',
		['price'] = 100000,
		['category'] = 'Tesla',
		['categoryLabel'] = 'Tesla',
		['hash'] = `tmodel`,
		['shop'] = 'pdm',
	},
	['teslax'] = {
		['name'] = 'Model X',
		['brand'] = 'Tesla',
		['model'] = 'teslax',
		['price'] = 100000,
		['category'] = 'Tesla',
		['categoryLabel'] = 'Tesla',
		['hash'] = `teslax`,
		['shop'] = 'pdm',
	},

	-- Toyota
	['a90sh'] = {
		['name'] = 'Supra MK5',
		['brand'] = 'Toyota',
		['model'] = 'a90sh',
		['price'] = 115000,
		['category'] = 'Toyota',
		['categoryLabel'] = 'Toyota',
		['hash'] = `a90sh`,
		['shop'] = 'pdm',
	},
	['toysupmk4'] = {
		['name'] = 'Supra MK4',
		['brand'] = 'Toyota',
		['model'] = 'toysupmk4',
		['price'] = 100000,
		['category'] = 'Toyota',
		['categoryLabel'] = 'Toyota',
		['hash'] = `toysupmk4`,
		['shop'] = 'pdm',
	},

	-- Volkswagen
	['passatr'] = {
		['name'] = 'Passat GTE',
		['brand'] = 'Volkswagen',
		['model'] = 'passatr',
		['price'] = 100000,
		['category'] = 'Volkswagen',
		['categoryLabel'] = 'Volkswagen',
		['hash'] = `passatr`,
		['shop'] = 'pdm',
	},

	-- Aston Martin
	['db11'] = {
		['name'] = 'DB11',
		['brand'] = 'Aston Martin',
		['model'] = 'db11',
		['price'] = 100000,
		['category'] = 'Aston Martin',
		['categoryLabel'] = 'Aston Martin',
		['hash'] = `db11`,
		['shop'] = 'pdm',
	},

	-- Other
	['tumbler'] = {
		['name'] = 'Tumbler',
		['brand'] = 'Batmobile',
		['model'] = 'tumbler',
		['price'] = 10000000,
		['category'] = 'Other',
		['categoryLabel'] = 'Other',
		['hash'] = `tumbler`,
		['shop'] = 'pdm',
	},
	['batpod'] = {
		['name'] = 'Pod',
		['brand'] = 'Batmobile',
		['model'] = 'batpod',
		['price'] = 10000000,
		['category'] = 'Other',
		['categoryLabel'] = 'Other',
		['hash'] = `batpod`,
		['shop'] = 'pdm',
	},
	
	['skart'] = {
		['name'] = 'Shopping',
		['brand'] = 'GoKart',
		['model'] = 'skart',
		['price'] = 10000000,
		['category'] = 'Other',
		['categoryLabel'] = 'Other',
		['hash'] = `skart`,
		['shop'] = 'pdm',
	},

	['sphere'] = {
		['name'] = 'Gyrosphere',
		['brand'] = 'Other',
		['model'] = 'sphere',
		['price'] = 1000000,
		['category'] = 'Other',
		['categoryLabel'] = 'Other',
		['hash'] = `sphere`,
		['shop'] = 'pdm',
	},

	['mrbeanmini'] = {
		['name'] = 'Mr Bean',
		['brand'] = 'Mini',
		['model'] = 'mrbeanmini',
		['price'] = 1000,
		['category'] = 'Other',
		['categoryLabel'] = 'Other',
		['hash'] = `mrbeanmini`,
		['shop'] = 'pdm',
	},
	
	--### END OF GROUND ###--
	--### AIR ###--
	-- Drones --

	--### END OF AIR ###--
	--### WATER ###--
	-- Boats --
	['magurav5'] = {
		['name'] = 'V5 USV',
		['brand'] = 'Magura',
		['model'] = 'magurav5',
		['price'] = 1000,
		['category'] = 'Boats',
		['categoryLabel'] = 'Boats',
		['hash'] = `magurav5`,
		['shop'] = 'water',
	},

	-- Yachts --
	-- Yaluxe (not enterable after exiting area)
	--['yaluxe'] = {
	--	['name'] = 'Super Yacht',
	--	['brand'] = 'Galaxy',
	--	['model'] = 'yaluxe',
	--	['price'] = 1000,
	--	['category'] = 'Yachts',
	--	['categoryLabel'] = 'Yachts',
	--	['hash'] = `yaluxe`,
	--	['shop'] = 'water',
	--},
	
	--### END OF WATER ###--
} -- DO NOT REMOVE THIS LINE --